Repository cptbtptp01/ideation-accessibilty, pull requests merged in 2024-03, with the labels that each got.

#38 Impl and test elbow method for automatic optimal k selection in k-means clustering
  src/components/groupingList.tsx
  src/grouping.tsx
  src/kMeansClustering.ts
  test/grouping.test.ts
  test/groupingColor.test.ts
  test/groupingDistance.test.ts
  test/mockBoardNodes.ts
Labels: bug, enhancement

#35 Impl & test cluster by type
  .prettierrc
  package-lock.json
  package.json
  src/components/activityList.tsx
  src/data/grouping/stickyColor.ts
  src/grouping.tsx
  src/index.ts
  test/groupingColor.test.ts
  test/groupingType.test.ts
  test/mockBoardNodes.ts
Labels: enhancement

#42 Impl preprocessing and code cleanup
  src/grouping.tsx
Labels: enhancement

#44 Groupping logic wrapper (WIP)
  src/grouping.tsx
Labels: enhancement

#45 minor update per discussion and latest grouping.tsx
  src/grouping.tsx
Labels: enhancement

#47 Fix output content bug
  src/grouping.tsx
Labels: bug

#53 Fix and test grouping by shape/type
  src/grouping.tsx
  src/kMeansClustering.ts
  test/groupingDistance.test.ts
Labels: bug, enhancement

#59 Evaluate grouping by color or type - Hopefully the last pr for grouping before Hackathon ddl...
  src/grouping.tsx
  src/kMeansClustering.ts
Labels: bug, enhancement

#64 Fix missing of arra len property bug
  src/grouping.tsx
Labels: bug

#61 Update Interface for grouping
  src/app.tsx
  src/assets/style.css
  src/components/groupingList.tsx
  src/grouping.tsx
Labels: enhancement, A11y

#67 Grouping frontend v2
  src/ai.tsx
  src/app.tsx
  src/assets/notification.wav
  src/components/activityList.tsx
  src/components/groupingList.tsx
Labels: enhancement
