Repository cptbtptp01/ideation-accessibilty, pull requests merged in 2024-02, with the labels that each got.

#12 fixed hex code issue
  package-lock.json
  package.json
  src/grouping.tsx
Labels: bug

#16 Grouping process framework
  src/grouping.tsx
Labels: design

#25 Add test module and Impl getLocation()
  jest.config.js
  package-lock.json
  package.json
  src/grouping.tsx
  test/grouping.test.ts
Labels: enhancement
